[workspace]
members = [".", "util", "util/macros"]
resolver = "2"

[package]
name = "allochronic"
version = "0.0.0-reserve"
description = "reserved crate"
license = "MIT OR Apache-2.0"
edition = "2018"
